export const data: IFootballClub[] = [
  {
    club: 'http://www.wikidata.org/entity/Q18522',
    clubLabel: 'Mansfield Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q619071',
    venueLabel: 'Field Mill',
    coordinates: 'Point(-1.200556 53.138056)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Mansfield_Town_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/7/7d/Mansfield_Town_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18526',
    clubLabel: 'Stockport County F.C.',
    venue: 'http://www.wikidata.org/entity/Q1284381',
    venueLabel: 'Edgeley Park',
    coordinates: 'Point(-2.166388888 53.399722222)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Stockport_County_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/4/43/Stockport_County_FC_logo_2020.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18523',
    clubLabel: 'Newport County A.F.C.',
    venue: 'http://www.wikidata.org/entity/Q2343802',
    venueLabel: 'Rodney Parade',
    coordinates: 'Point(-2.987778 51.588333)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Newport_County_A.F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/b/b0/Newport_County_crest.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18520',
    clubLabel: 'Luton Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q1613767',
    venueLabel: 'Kenilworth Road',
    coordinates: 'Point(-0.431666666 51.884166666)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Luton_Town_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/9/9d/Luton_Town_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18519',
    clubLabel: 'Lincoln City F.C.',
    venue: 'http://www.wikidata.org/entity/Q619105',
    venueLabel: 'Sincil Bank',
    coordinates: 'Point(-0.540811 53.218289)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Lincoln_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/f/f1/Lincoln_City_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q2714',
    clubLabel: 'Watford F.C.',
    venue: 'http://www.wikidata.org/entity/Q10626',
    venueLabel: 'Vicarage Road',
    coordinates: 'Point(-0.401606 51.649928)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Watford_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/e/e2/Watford.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q5794',
    clubLabel: 'Everton F.C.',
    venue: 'http://www.wikidata.org/entity/Q968420',
    venueLabel: 'Goodison Park',
    coordinates: 'Point(-2.966388888 53.438888888)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Everton_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18515',
    clubLabel: 'Grimsby Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q3641228',
    venueLabel: 'Blundell Park',
    coordinates: 'Point(-0.046497 53.570225)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Grimsby_Town_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/d/db/Grimsby_Town_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18509',
    clubLabel: 'Cambridge United F.C.',
    venue: 'http://www.wikidata.org/entity/Q2444574',
    venueLabel: 'Abbey Stadium',
    coordinates: 'Point(0.153 52.2114)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Cambridge_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/8/8f/Cambridge_United_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18507',
    clubLabel: 'Barrow A.F.C.',
    venue: 'http://www.wikidata.org/entity/Q619563',
    venueLabel: 'Holker Street',
    coordinates: 'Point(-3.235 54.123333333)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Barrow_A.F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/2/28/Barrow_AFC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18460',
    clubLabel: 'Salford City F.C.',
    venue: 'http://www.wikidata.org/entity/Q54817852',
    venueLabel: 'Moor Lane',
    coordinates: 'Point(-2.276777777 53.513638888)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Salford_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/f/f3/Salford_City_FC_Logo.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q9426',
    clubLabel: 'Stevenage F.C.',
    venue: 'http://www.wikidata.org/entity/Q619353',
    venueLabel: 'Broadhall Way',
    coordinates: 'Point(-0.193608 51.889839)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Stevenage_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/commons/4/45/Stevenage_Football_Club.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48879',
    clubLabel: 'Bradford City A.F.C.',
    venue: 'http://www.wikidata.org/entity/Q969279',
    venueLabel: 'Valley Parade',
    coordinates: 'Point(-1.759022222 53.804222222)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Bradford_City_A.F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/3/32/Bradford_City_AFC.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48851',
    clubLabel: 'AFC Wimbledon',
    venue: 'http://www.wikidata.org/entity/Q48699006',
    venueLabel: 'Plough Lane',
    coordinates: 'Point(-0.186669444 51.431363888)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/AFC_Wimbledon',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/1/1b/AFC_Wimbledon_%282020%29_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48925',
    clubLabel: 'Bristol Rovers F.C.',
    venue: 'http://www.wikidata.org/entity/Q508121',
    venueLabel: 'Memorial Stadium (Bristol)',
    coordinates: 'Point(-2.58313 51.4862)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Bristol_Rovers_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/4/47/Bristol_Rovers_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q9616',
    clubLabel: 'Chelsea F.C.',
    venue: 'http://www.wikidata.org/entity/Q171458',
    venueLabel: 'Stamford Bridge',
    coordinates: 'Point(-0.191111111 51.481666666)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Chelsea_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48950',
    clubLabel: 'Rotherham United F.C.',
    venue: 'http://www.wikidata.org/entity/Q1983118',
    venueLabel: 'New York Stadium',
    coordinates: 'Point(-1.362 53.4279)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Rotherham_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/c/c0/Rotherham_United_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48948',
    clubLabel: 'Port Vale F.C.',
    venue: 'http://www.wikidata.org/entity/Q1724993',
    venueLabel: 'Vale Park',
    coordinates: 'Point(-2.1925 53.049722)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Port_Vale_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/5/5f/Port_Vale_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18708',
    clubLabel: 'Fulham F.C.',
    venue: 'http://www.wikidata.org/entity/Q318043',
    venueLabel: 'Craven Cottage',
    coordinates: 'Point(-0.221666666 51.475)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Fulham_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18656',
    clubLabel: 'Manchester United F.C.',
    venue: 'http://www.wikidata.org/entity/Q83457',
    venueLabel: 'Old Trafford',
    coordinates: 'Point(-2.291388888 53.463055555)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Manchester_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18716',
    clubLabel: 'Newcastle United F.C.',
    venue: 'http://www.wikidata.org/entity/Q191774',
    venueLabel: 'St James’ Park',
    coordinates: 'Point(-1.621666666 54.975555555)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Newcastle_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q50602',
    clubLabel: 'Manchester City F.C.',
    venue: 'http://www.wikidata.org/entity/Q48159',
    venueLabel: 'Etihad Stadium',
    coordinates: 'Point(-2.200277777 53.483055555)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Manchester_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q9617',
    clubLabel: 'Arsenal F.C.',
    venue: 'http://www.wikidata.org/entity/Q163995',
    venueLabel: 'Emirates Stadium',
    coordinates: 'Point(-0.108611111 51.555)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Arsenal_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18741',
    clubLabel: 'Tottenham Hotspur F.C.',
    venue: 'http://www.wikidata.org/entity/Q55074091',
    venueLabel: 'Tottenham Hotspur Stadium',
    coordinates: 'Point(-0.066388888 51.604444444)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Tottenham_Hotspur_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18711',
    clubLabel: 'Aston Villa F.C.',
    venue: 'http://www.wikidata.org/entity/Q175339',
    venueLabel: 'Villa Park',
    coordinates: 'Point(-1.884722222 52.509166666)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Aston_Villa_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/9/9f/Aston_Villa_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18723',
    clubLabel: 'Queens Park Rangers F.C.',
    venue: 'http://www.wikidata.org/entity/Q31670',
    venueLabel: 'Kiyan Prince Foundation Stadium',
    coordinates: 'Point(-0.232222222 51.509166666)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Queens_Park_Rangers_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/3/31/Queens_Park_Rangers_crest.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18721',
    clubLabel: 'Norwich City F.C.',
    venue: 'http://www.wikidata.org/entity/Q123017',
    venueLabel: 'Carrow Road',
    coordinates: 'Point(1.309166666 52.622222222)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Norwich_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/1/17/Norwich_City_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48939',
    clubLabel: 'Exeter City F.C.',
    venue: 'http://www.wikidata.org/entity/Q1856701',
    venueLabel: 'St James Park',
    coordinates: 'Point(-3.52115 50.730713888)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Exeter_City_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/7/71/Exeter_City_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48929',
    clubLabel: 'Burton Albion F.C.',
    venue: 'http://www.wikidata.org/entity/Q619136',
    venueLabel: 'Pirelli Stadium',
    coordinates: 'Point(-1.626958 52.821906)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Burton_Albion_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/5/53/Burton_Albion_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48932',
    clubLabel: 'Cheltenham Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q541299',
    venueLabel: 'Whaddon Road',
    coordinates: 'Point(-2.060211 51.906158)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Cheltenham_Town_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/c/c3/Cheltenham_Town_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18729',
    clubLabel: 'Reading F.C.',
    venue: 'http://www.wikidata.org/entity/Q31656',
    venueLabel: 'Madejski Stadium',
    coordinates: 'Point(-0.982777777 51.422222222)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Reading_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/1/11/Reading_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19444',
    clubLabel: 'Birmingham City F.C.',
    venue: 'http://www.wikidata.org/entity/Q819179',
    venueLabel: "St Andrew's",
    coordinates: 'Point(-1.868188888 52.475702777)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Birmingham_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/6/68/Birmingham_City_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19442',
    clubLabel: 'Barnsley F.C.',
    venue: 'http://www.wikidata.org/entity/Q1138270',
    venueLabel: 'Oakwell',
    coordinates: 'Point(-1.4675 53.552222)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Barnsley_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/c/c9/Barnsley_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19637',
    clubLabel: 'Tranmere Rovers F.C.',
    venue: 'http://www.wikidata.org/entity/Q619072',
    venueLabel: 'Prenton Park',
    coordinates: 'Point(-3.0325 53.373722)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Tranmere_Rovers_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/e/e6/Tranmere_Rovers_FC_logo.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19644',
    clubLabel: 'Walsall F.C.',
    venue: 'http://www.wikidata.org/entity/Q609268',
    venueLabel: 'Bescot Stadium',
    coordinates: 'Point(-1.990706 52.565433)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Walsall_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/e/ef/Walsall_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48843',
    clubLabel: 'Accrington Stanley F.C.',
    venue: 'http://www.wikidata.org/entity/Q620815',
    venueLabel: 'Crown Ground',
    coordinates: 'Point(-2.370911 53.765356)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Accrington_Stanley_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/b/ba/Accrington_Stanley_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18732',
    clubLabel: 'Southampton F.C.',
    venue: 'http://www.wikidata.org/entity/Q567339',
    venueLabel: "St Mary's Stadium",
    coordinates: 'Point(-1.39111111 50.90583333)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Southampton_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/c/c9/FC_Southampton.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18736',
    clubLabel: 'Stoke City F.C.',
    venue: 'http://www.wikidata.org/entity/Q500922',
    venueLabel: 'Britannia Stadium',
    coordinates: 'Point(-2.175555555 52.988333333)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Stoke_City_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/2/29/Stoke_City_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18739',
    clubLabel: 'Sunderland A.F.C.',
    venue: 'http://www.wikidata.org/entity/Q31969',
    venueLabel: 'Stadium of Light',
    coordinates: 'Point(-1.3882 54.9144)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Sunderland_A.F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/7/77/Logo_Sunderland.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19446',
    clubLabel: 'Blackburn Rovers F.C.',
    venue: 'http://www.wikidata.org/entity/Q245085',
    venueLabel: 'Ewood Park',
    coordinates: 'Point(-2.489166666 53.728611111)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Blackburn_Rovers_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/0/0f/Blackburn_Rovers.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18750',
    clubLabel: 'Wigan Athletic F.C.',
    venue: 'http://www.wikidata.org/entity/Q494388',
    venueLabel: 'DW Stadium',
    coordinates: 'Point(-2.653889 53.547778)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Wigan_Athletic_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/4/43/Wigan_Athletic.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q9653',
    clubLabel: 'Ipswich Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q619558',
    venueLabel: 'Portman Road',
    coordinates: 'Point(1.144830555 52.055061111)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Ipswich_Town_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/4/43/Ipswich_Town.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48943',
    clubLabel: 'Gillingham F.C.',
    venue: 'http://www.wikidata.org/entity/Q619148',
    venueLabel: 'Priestfield Stadium',
    coordinates: 'Point(0.560833333 51.384166666)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Gillingham_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/5/5e/FC_Gillingham_Logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48944',
    clubLabel: 'Morecambe F.C.',
    venue: 'http://www.wikidata.org/entity/Q762987',
    venueLabel: 'Globe Arena',
    coordinates: 'Point(-2.86716 54.0615)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Morecambe_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/b/bd/Morecambe_FC.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48941',
    clubLabel: 'Fleetwood Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q619024',
    venueLabel: 'Highbury Stadium',
    coordinates: 'Point(-3.024728 53.916508)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Fleetwood_Town_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/e/ed/Fleetwood_Town_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19449',
    clubLabel: 'Blackpool F.C.',
    venue: 'http://www.wikidata.org/entity/Q870859',
    venueLabel: 'Bloomfield Road',
    coordinates: 'Point(-3.048056 53.804722)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Blackpool_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/d/df/Blackpool_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19451',
    clubLabel: 'Bolton Wanderers F.C.',
    venue: 'http://www.wikidata.org/entity/Q242772',
    venueLabel: 'Toughsheet Community Stadium',
    coordinates: 'Point(-2.535555555 53.580555555)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Bolton_Wanderers_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/8/82/Bolton_Wanderers_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19462',
    clubLabel: 'Charlton Athletic F.C.',
    venue: 'http://www.wikidata.org/entity/Q958319',
    venueLabel: 'The Valley',
    coordinates: 'Point(0.035632 51.487489)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Charlton_Athletic_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/commons/6/6a/CharltonBadge_30Jan2020.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19467',
    clubLabel: 'Crystal Palace F.C.',
    venue: 'http://www.wikidata.org/entity/Q1066373',
    venueLabel: 'Selhurst Park',
    coordinates: 'Point(-0.085555555 51.398333333)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Crystal_Palace_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19458',
    clubLabel: 'Burnley F.C.',
    venue: 'http://www.wikidata.org/entity/Q683112',
    venueLabel: 'Turf Moor',
    coordinates: 'Point(-2.230225 53.789064)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Burnley_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/6/6d/Burnley_FC_Logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19456',
    clubLabel: 'Bristol City F.C.',
    venue: 'http://www.wikidata.org/entity/Q726370',
    venueLabel: 'Ashton Gate Stadium',
    coordinates: 'Point(-2.620278 51.44)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Bristol_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/f/f5/Bristol_City_crest.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18747',
    clubLabel: 'West Ham United F.C.',
    venue: 'http://www.wikidata.org/entity/Q172190',
    venueLabel: 'London Stadium',
    coordinates: 'Point(-0.016388888 51.538611111)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/West_Ham_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18744',
    clubLabel: 'West Bromwich Albion F.C.',
    venue: 'http://www.wikidata.org/entity/Q31678',
    venueLabel: 'The Hawthorns',
    coordinates: 'Point(-1.963888888 52.509166666)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/West_Bromwich_Albion_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/8/8b/West_Bromwich_Albion.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19453',
    clubLabel: 'Brighton & Hove Albion F.C.',
    venue: 'http://www.wikidata.org/entity/Q619409',
    venueLabel: 'Brighton Community Stadium',
    coordinates: 'Point(-0.083277777 50.861822222)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Brighton_%26_Hove_Albion_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18659',
    clubLabel: 'Swansea City A.F.C.',
    venue: 'http://www.wikidata.org/entity/Q580480',
    venueLabel: 'Liberty Stadium',
    coordinates: 'Point(-3.9351 51.6422)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Swansea_City_A.F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/f/f9/Swansea_City_AFC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19470',
    clubLabel: 'Derby County F.C.',
    venue: 'http://www.wikidata.org/entity/Q201612',
    venueLabel: 'Pride Park Stadium',
    coordinates: 'Point(-1.447222222 52.915)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Derby_County_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/4/4a/Derby_County_crest.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19473',
    clubLabel: 'Huddersfield Town A.F.C.',
    venue: 'http://www.wikidata.org/entity/Q619407',
    venueLabel: 'Kirklees Stadium',
    coordinates: 'Point(-1.768333333 53.654166666)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Huddersfield_Town_A.F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/7/7d/Huddersfield_Town_A.F.C._logo.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19477',
    clubLabel: 'Hull City A.F.C.',
    venue: 'http://www.wikidata.org/entity/Q630160',
    venueLabel: 'MKM Stadium',
    coordinates: 'Point(-0.367777777 53.746111111)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Hull_City_A.F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/5/54/Hull_City_A.F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19481',
    clubLabel: 'Leicester City F.C.',
    venue: 'http://www.wikidata.org/entity/Q620031',
    venueLabel: 'Leicester City Stadium',
    coordinates: 'Point(-1.142222222 52.620277777)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Leicester_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/2/2d/Leicester_City_crest.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19490',
    clubLabel: 'Nottingham Forest F.C.',
    venue: 'http://www.wikidata.org/entity/Q593446',
    venueLabel: 'City Ground',
    coordinates: 'Point(-1.132778 52.94)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Nottingham_Forest_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/e/e5/Nottingham_Forest_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19487',
    clubLabel: 'Millwall F.C.',
    venue: 'http://www.wikidata.org/entity/Q908481',
    venueLabel: 'The Den',
    coordinates: 'Point(-0.050833 51.485833)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Millwall_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/7/71/Millwall_FC_logo.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19495',
    clubLabel: 'Peterborough United F.C.',
    venue: 'http://www.wikidata.org/entity/Q1156350',
    venueLabel: 'London Road Stadium',
    coordinates: 'Point(-0.240389 52.564694)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Peterborough_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/d/d4/Peterborough_United.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19498',
    clubLabel: 'Sheffield Wednesday F.C.',
    venue: 'http://www.wikidata.org/entity/Q642557',
    venueLabel: 'Hillsborough Stadium',
    coordinates: 'Point(-1.500555555 53.411388888)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Sheffield_Wednesday_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/8/88/Sheffield_Wednesday_badge.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19575',
    clubLabel: 'Carlisle United F.C.',
    venue: 'http://www.wikidata.org/entity/Q994219',
    venueLabel: 'Brunton Park',
    coordinates: 'Point(-2.91365 54.89556)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Carlisle_United_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/6/63/Carl_Badge.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19578',
    clubLabel: 'Colchester United F.C.',
    venue: 'http://www.wikidata.org/entity/Q1141371',
    venueLabel: 'Colchester Community Stadium',
    coordinates: 'Point(0.897703 51.9234)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Colchester_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/6/65/Colchester_United_crest.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48947',
    clubLabel: 'Plymouth Argyle F.C.',
    venue: 'http://www.wikidata.org/entity/Q619350',
    venueLabel: 'Home Park',
    coordinates: 'Point(-4.150833333 50.388055555)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Plymouth_Argyle_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/a/a8/Plymouth_Argyle_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48946',
    clubLabel: 'Oxford United F.C.',
    venue: 'http://www.wikidata.org/entity/Q1672134',
    venueLabel: 'Kassam Stadium',
    coordinates: 'Point(-1.208067 51.716419)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Oxford_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/3/3e/Oxford_United_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48945',
    clubLabel: 'Northampton Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q619615',
    venueLabel: 'Sixfields Stadium',
    coordinates: 'Point(-0.93345 52.235197)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Northampton_Town_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/2/2d/Northampton_Town_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q1130849',
    clubLabel: 'Liverpool F.C.',
    venue: 'http://www.wikidata.org/entity/Q45671',
    venueLabel: 'Anfield',
    coordinates: 'Point(-2.960833333 53.430833333)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Liverpool_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19500',
    clubLabel: 'Wolverhampton Wanderers F.C.',
    venue: 'http://www.wikidata.org/entity/Q380823',
    venueLabel: 'Molineux Stadium',
    coordinates: 'Point(-2.130277777 52.590277777)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Wolverhampton_Wanderers_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/f/fc/Wolverhampton_Wanderers.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q1128631',
    clubLabel: 'Leeds United F.C.',
    venue: 'http://www.wikidata.org/entity/Q619505',
    venueLabel: 'Elland Road',
    coordinates: 'Point(-1.572222222 53.777777777)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Leeds_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/5/54/Leeds_United_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18662',
    clubLabel: 'Cardiff City F.C.',
    venue: 'http://www.wikidata.org/entity/Q867902',
    venueLabel: 'Cardiff City Stadium',
    coordinates: 'Point(-3.203056 51.472778)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Cardiff_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/3/3c/Cardiff_City_crest.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q18661',
    clubLabel: 'Middlesbrough F.C.',
    venue: 'http://www.wikidata.org/entity/Q822886',
    venueLabel: 'Riverside Stadium',
    coordinates: 'Point(-1.216944444 54.578333333)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Middlesbrough_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/2/2c/Middlesbrough_FC_crest.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19587',
    clubLabel: 'Crewe Alexandra F.C.',
    venue: 'http://www.wikidata.org/entity/Q389544',
    venueLabel: 'Alexandra Stadium',
    coordinates: 'Point(-2.435747 53.087419)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Crewe_Alexandra_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/9/9d/Crewe_Alexandra.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19580',
    clubLabel: 'Coventry City F.C.',
    venue: 'http://www.wikidata.org/entity/Q842077',
    venueLabel: 'Ricoh Arena',
    coordinates: 'Point(-1.495556 52.448056)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Coventry_City_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/1/1a/Coventry_City_F.C._logo.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19584',
    clubLabel: 'Crawley Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q609115',
    venueLabel: 'The Peoples Pension Stadium',
    coordinates: 'Point(-0.194767 51.099706)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Crawley_Town_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/8/8b/Crawley_Town_FC_logo.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19568',
    clubLabel: 'AFC Bournemouth',
    venue: 'http://www.wikidata.org/entity/Q619094',
    venueLabel: 'Dean Court',
    coordinates: 'Point(-1.838333 50.735278)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/AFC_Bournemouth',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19571',
    clubLabel: 'Brentford F.C.',
    venue: 'http://www.wikidata.org/entity/Q1546623',
    venueLabel: 'Griffin Park',
    coordinates: 'Point(-0.302639 51.488167)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Brentford_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19592',
    clubLabel: 'Hartlepool United F.C.',
    venue: 'http://www.wikidata.org/entity/Q538115',
    venueLabel: 'Victoria Park',
    coordinates: 'Point(-1.212722 54.689139)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Hartlepool_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/3/37/Hartlepool_United_FC_logo_2017.png',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19595',
    clubLabel: 'Leyton Orient F.C.',
    venue: 'http://www.wikidata.org/entity/Q917727',
    venueLabel: 'Brisbane Road',
    coordinates: 'Point(-0.012639 51.560139)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Leyton_Orient_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/a/a8/Leyton_Orient_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19589',
    clubLabel: 'Doncaster Rovers F.C.',
    venue: 'http://www.wikidata.org/entity/Q1336402',
    venueLabel: 'Keepmoat Stadium',
    coordinates: 'Point(-1.113889 53.509722)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Doncaster_Rovers_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/c/c5/Doncaster_Rovers_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19598',
    clubLabel: 'Notts County F.C.',
    venue: 'http://www.wikidata.org/entity/Q1192396',
    venueLabel: 'Meadow Lane',
    coordinates: 'Point(-1.137222 52.9425)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Notts_County_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/2/2e/Notts_County_Logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19604',
    clubLabel: 'Portsmouth F.C.',
    venue: 'http://www.wikidata.org/entity/Q619531',
    venueLabel: 'Fratton Park',
    coordinates: 'Point(-1.063888888 50.796388888)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Portsmouth_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/3/38/Portsmouth_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19615',
    clubLabel: 'Scunthorpe United F.C.',
    venue: 'http://www.wikidata.org/entity/Q619256',
    venueLabel: 'Glanford Park',
    coordinates: 'Point(-0.69525 53.586722)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Scunthorpe_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/9/95/Scunthorpe_United_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19626',
    clubLabel: 'Shrewsbury Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q619070',
    venueLabel: 'New Meadow',
    coordinates: 'Point(-2.74933 52.68863)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Shrewsbury_Town_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/1/1b/Shrewsbury_Town_F.C._logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q2219286',
    clubLabel: 'Harrogate Town A.F.C.',
    venue: 'http://www.wikidata.org/entity/Q28195119',
    venueLabel: 'Wetherby Road',
    coordinates: 'Point(-1.514444444 53.991666666)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Harrogate_Town_A.F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/4/40/Harrogate_Town_AFC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19612',
    clubLabel: 'Preston North End F.C.',
    venue: 'http://www.wikidata.org/entity/Q1141958',
    venueLabel: 'Deepdale',
    coordinates: 'Point(-2.688055555 53.772222222)',
    league: 'http://www.wikidata.org/entity/Q19510',
    leagueLabel: 'EFL Championship',
    article: 'https://en.wikipedia.org/wiki/Preston_North_End_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/8/82/Preston_North_End_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19607',
    clubLabel: 'Sheffield United F.C.',
    venue: 'http://www.wikidata.org/entity/Q897533',
    venueLabel: 'Bramall Lane',
    coordinates: 'Point(-1.470833333 53.370277777)',
    league: 'http://www.wikidata.org/entity/Q9448',
    leagueLabel: 'Premier League',
    article: 'https://en.wikipedia.org/wiki/Sheffield_United_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/9/9c/Sheffield_United_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q19634',
    clubLabel: 'Swindon Town F.C.',
    venue: 'http://www.wikidata.org/entity/Q1137293',
    venueLabel: 'County Ground, Swindon',
    coordinates: 'Point(-1.770556 51.564444)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Swindon_Town_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/a/a3/Swindon_Town_FC.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q48953',
    clubLabel: 'Wycombe Wanderers F.C.',
    venue: 'http://www.wikidata.org/entity/Q351946',
    venueLabel: 'Adams Park',
    coordinates: 'Point(-0.800277777 51.630555555)',
    league: 'http://www.wikidata.org/entity/Q19565',
    leagueLabel: 'EFL League One',
    article: 'https://en.wikipedia.org/wiki/Wycombe_Wanderers_F.C.',
    badgeLink:
      '//upload.wikimedia.org/wikipedia/en/f/fb/Wycombe_Wanderers_FC_logo.svg',
  },
  {
    club: 'http://www.wikidata.org/entity/Q248188',
    clubLabel: 'Milton Keynes Dons F.C.',
    venue: 'http://www.wikidata.org/entity/Q1144973',
    venueLabel: 'Stadium MK',
    coordinates: 'Point(-0.733333 52.009444)',
    league: 'http://www.wikidata.org/entity/Q48837',
    leagueLabel: 'EFL League Two',
    article: 'https://en.wikipedia.org/wiki/Milton_Keynes_Dons_F.C.',
    badgeLink: '//upload.wikimedia.org/wikipedia/en/b/bf/MK_Dons.png',
  },
];
